# Generated by Django 3.2.3 on 2025-03-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('uuid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('balance', models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
